"""
Django settings for Bookify_Hub_Services project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
from os import environ, getenv, path
from decouple import config
from Bookify_Hub_Services.aws import get_aws_credentials
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%zupo)0dum#c12*@$%re8c9koqf7!l6o(do$q3a3x95ece^=_f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ServiceHub',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True



CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'DELETE',
    'PATCH',
    'PUT'
]
CORS_ALLOW_HEADERS = (
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'X-CSRFToken',
    'Access-Control-Allow-Origin',
    'Access-Control-Allow-Headers',
    'Access-Control-Allow-Methods'
)
ROOT_URLCONF = 'Bookify_Hub_Services.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            path.join(BASE_DIR, 'ServiceHub/html_templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Bookify_Hub_Services.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
# AWS Configuration
AWS_CREDENTIALS = get_aws_credentials()

# environ['ATLAS_SRV']=config('ATLAS_SRV')
# environ['MONGO_DB'] ='bookifydB'
# environ['ENV'] = 'local'
# environ["AWS_ACCESS_KEY_ID"] = config('AWS_ACCESS_KEY')
# environ["AWS_SECRET_KEY"] = config('AWS_SECRET_KEY')
# environ['AWS_S3_BUCKET_NAME'] = 'bookifyadmin'
# environ['AWS_S3_BUCKET_BASE_URL'] = 'http://bookifyadmin.s3-website-us-east-1.amazonaws.com'
environ['API_V1_ENDPOINT'] = 'http://127.0.0.1:8000/'

AWS_ACCESS_KEY = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_BUCKET_NAME = os.getenv('AWS_S3_BUCKET_NAME')
AWS_S3_BUCKET_BASE_URL = os.getenv('AWS_S3_BUCKET_BASE_URL')
API_V1_ENDPOINT = os.getenv('API_V1_ENDPOINT')
ATLAS_SRV = os.getenv('ATLAS_SRV')
MONGO_DB = os.getenv('MONGO_DB')

# NODE_SERVER = getenv('NODE_SERVER')
# OPENAI_APIKEY = getenv('OPENAI_APIKEY')
# API_IDENTITY_SERVICE = getenv('API_IDENTITY_SERVICE')

ENV = getenv('ENV')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'http://bookifyadmin.s3-website-us-east-1.amazonaws.com/'
# STATIC_ROOT = '/app/staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# source /Users/ramzianishamudheen/Desktop/Services/env/bin/activate

# MongoDb Atlas connections
ATLAS_CONNECTION_STRING = str(getenv('ATLAS_SRV'))
MONGO_DB = str(getenv('MONGO_DB'))